[package]
name = "ckb-pcn-cross-chain-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bitcoind = { version = "0.34.1", features = ["25_1"] }
